### ISSUE TITLE
Login failed and docker stopped

### ISSUE THREAD

**Issue by Akira46** [doubleTroub1e/nodepayai#1]
I'm having trouble running on docker. I get an error and it stops the process.
`{'level': 'SEVERE', 'message': 'https://www.googletagmanager.com/gtm.js?id=GTM-PQM39PC2 - Failed to load resource: net::ERR_CONNECTION_REFUSED', 'source': 'network', 'timestamp': 1717139762601}
{'level': 'SEVERE', 'message': 'https://app.nodepay.ai/login - Error while trying to use the following icon from the Manifest: https://app.nodepay.ai/favicon.png (Resource size is not correct - typo in the Manifest?)', 'source': 'other', 'timestamp': 1717139766725}
{'level': 'SEVERE', 'message': "https://app.nodepay.ai/login - Access to fetch at 'https://api.nodepay.ai/api/auth/login?' from origin 'https://app.nodepay.ai' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.", 'source': 'javascript', 'timestamp': 1717139774415}
{'level': 'SEVERE', 'message': 'https://api.nodepay.ai/api/auth/login? - Failed to load resource: net::ERR_FAILED', 'source': 'network', 'timestamp': 1717139774421}
`
can you help me to fix this problem

**Comment by doubleTroub1e** [comment]
also can't solve. and even undetected headless doesn't work, not that good with selenium)
anyway, you can start this container, manually sign in and it should work
https://github.com/vital987/chrome-novnc
if another architecture is needed (like for raspberry pi) then you can pull image double2trouble/nodepay:chromium-v1

**Comment by Akira46** [comment]
I have installed the image double2trouble/nodepay:chromium-v1 in my docker, but I am confused about what to do next? there are no instructions for use

**Comment by doubleTroub1e** [comment]
if you start it like this 
`docker run \
    --name chrome-novnc \
    -e PORT=8080 \
    -p 8080:8080 \
    -e VNC_PASS=CHANGE_IT \
    -d vital987/chrome-novnc:latest`
    
    then go to http://IP_OF_DEVICE:8080  (like http://192.168.1.15:8080)
    enter password "CHANGE_IT" and manually install extension to chrome and login 
    
    this is how I'm using it now on raspberry pi 4

**Comment by doubleTroub1e** [comment]
@Akira46  you can try now use again my docker image, it is working fine for me now, seems yesterday smth was wrong (also my IP is changed today, os probably it was IP block yesterday)
