### ISSUE TITLE
nodepay.ai

### ISSUE THREAD

**Issue by Solana0x** [doubleTroub1e/nodepayai#3]
How to run the script without docker? why to waste so much of resoruces in docker??

this is WEBSOCKET_URL = "wss://nw.nodepay.ai:4576/websocket"

**Comment by YiMoWanXia** [comment]
> 如何在没有 docker 的情况下运行脚本？为什么要在 docker 中浪费那么多资源？
> 
> 这是 WEBSOCKET_URL = “wss://nw.nodepay.ai:4576/websocket”

I already have a script written.

**Comment by Solana0x** [comment]
@YiMoWanXia can you share the script? my script aint working its giving Internal Errors and such similar errors it would be great if you share your script

**Comment by YiMoWanXia** [comment]
> @YiMoWanXia can you share the script? my script aint working its giving Internal Errors and such similar errors it would be great if you share your script

not free
