### ISSUE TITLE
Node Pay Login Recaptcha

### ISSUE THREAD

**Issue by engageub** [doubleTroub1e/nodepayai#4]
Hi,
I just had a look at the code. The login page shows recaptcha but the existing code does not seem to handle recaptcha.
Could you please use the following recaptcha solver in chrome browser .

https://chromewebstore.google.com/detail/rektcaptcha-recaptcha-sol/bbdhfoclddncoaomddgkaaphcnddbpdh

Thank you

**Comment by doubleTroub1e** [comment]
Hi @engageub,

seems this won't work that easy, you can try to start this version
https://github.com/aston668334/nodepay-socks-python

it is working for me just perfect, the only thing - I can't use proxy as of now, but hope this is temporary
